//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentalDisplay.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup
    {
        public int SetupId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> CompoundId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public string SetupName { get; set; }
        public string Results { get; set; }
        public Nullable<System.DateTime> DateOfMeasurement { get; set; }
    
        public virtual Compound Compound { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Location Location { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
